//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Common.Resource.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.
        /// </summary>
        public static string AnUnknownError {
            get {
                return ResourceManager.GetString("AnUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012.
        /// </summary>
        public static string CategoryCodeNotEmpty {
            get {
                return ResourceManager.GetString("CategoryCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 013.
        /// </summary>
        public static string CategoryNameNotEmpty {
            get {
                return ResourceManager.GetString("CategoryNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014.
        /// </summary>
        public static string ConversionUnitIdNotEmpty {
            get {
                return ResourceManager.GetString("ConversionUnitIdNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        public static string DuplicateConversionUnit {
            get {
                return ResourceManager.GetString("DuplicateConversionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002.
        /// </summary>
        public static string DuplicateMaterial {
            get {
                return ResourceManager.GetString("DuplicateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003.
        /// </summary>
        public static string DuplicateMaterialCategory {
            get {
                return ResourceManager.GetString("DuplicateMaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004.
        /// </summary>
        public static string DuplicateStock {
            get {
                return ResourceManager.GetString("DuplicateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005.
        /// </summary>
        public static string DuplicateUnit {
            get {
                return ResourceManager.GetString("DuplicateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 017.
        /// </summary>
        public static string FeatureNotEmpty {
            get {
                return ResourceManager.GetString("FeatureNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015.
        /// </summary>
        public static string MaterialCodeNotEmpty {
            get {
                return ResourceManager.GetString("MaterialCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016.
        /// </summary>
        public static string MaterialNameNotEmpty {
            get {
                return ResourceManager.GetString("MaterialNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string NoDefine {
            get {
                return ResourceManager.GetString("NoDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009.
        /// </summary>
        public static string NotExistOrDeleted {
            get {
                return ResourceManager.GetString("NotExistOrDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011.
        /// </summary>
        public static string StockCodeNotEmpty {
            get {
                return ResourceManager.GetString("StockCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018.
        /// </summary>
        public static string StockNameNotEmpty {
            get {
                return ResourceManager.GetString("StockNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010.
        /// </summary>
        public static string UnitNameNotEmpty {
            get {
                return ResourceManager.GetString("UnitNameNotEmpty", resourceCulture);
            }
        }
    }
}
