//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.CukCuk.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.CukCuk.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server không tìm thấy bất kì tài nguyên nào, bản ghi không tồn tại.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt được exception.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào trong database hoặc nó đã được xóa trước đó.
        /// </summary>
        public static string DevMsg_GetFail {
            get {
                return ResourceManager.GetString("DevMsg_GetFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server không tìm thấy bất kì tài nguyên nào, gọi procedure trong database thất bại.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string DevMsg_InvalidData {
            get {
                return ResourceManager.GetString("DevMsg_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi xảy ra server.
        /// </summary>
        public static string DevMsg_ServerError {
            get {
                return ResourceManager.GetString("DevMsg_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server không tìm thấy bất kì tài nguyên nào, bản ghi không tồn tại.
        /// </summary>
        public static string DevMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm nguyên vật liệu không được bỏ trống.
        /// </summary>
        public static string UserMsg_CategoryCodeNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_CategoryCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm nguyên vật liệu không được bỏ trống.
        /// </summary>
        public static string UserMsg_CategoryNameNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_CategoryNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được bỏ trống.
        /// </summary>
        public static string UserMsg_ConversionUnitIdNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_ConversionUnitIdNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thất bại, vui lòng thử lại.
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống.
        /// </summary>
        public static string UserMsg_DuplicateCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống.
        /// </summary>
        public static string UserMsg_DuplicateCode1 {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được hỗ trợ.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính chất không được bỏ trống.
        /// </summary>
        public static string UserMsg_FeatureNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_FeatureNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thất bại, vui lòng thử lại.
        /// </summary>
        public static string UserMsg_InsertFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không đúng định dạng.
        /// </summary>
        public static string UserMsg_InvalidCode {
            get {
                return ResourceManager.GetString("UserMsg_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_InvalidData {
            get {
                return ResourceManager.GetString("UserMsg_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string UserMsg_InvalidEmail {
            get {
                return ResourceManager.GetString("UserMsg_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id không được bỏ trống.
        /// </summary>
        public static string UserMsg_KeyAttribue {
            get {
                return ResourceManager.GetString("UserMsg_KeyAttribue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nguyên vật liệu không được bỏ trống.
        /// </summary>
        public static string UserMsg_MaterialCodeNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_MaterialCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nguyên vật liệu không được bỏ trống.
        /// </summary>
        public static string UserMsg_MaterialNameNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_MaterialNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thiếu số bản ghi trên trang.
        /// </summary>
        public static string UserMsg_PageSize {
            get {
                return ResourceManager.GetString("UserMsg_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_ServerError {
            get {
                return ResourceManager.GetString("UserMsg_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho không được bỏ trống.
        /// </summary>
        public static string UserMsg_StockCodeNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_StockCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho không được bỏ trống.
        /// </summary>
        public static string UserMsg_StockNameNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_StockNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị tính không được bỏ trống.
        /// </summary>
        public static string UserMsg_UnitNameNotEmpty {
            get {
                return ResourceManager.GetString("UserMsg_UnitNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thất bại, vui lòng thử lại.
        /// </summary>
        public static string UserMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdateFailed", resourceCulture);
            }
        }
    }
}
